apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-deployment
  namespace: boardgame
  labels:
    app: boardgame
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boardgame
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      imagePullSecrets:
        - name: nexus-creds
      containers:
        - name: boardgame
          image: 13.232.157.203:8000/boardgame:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: boardgame-svc
  namespace: boardgame
spec:
  type: NodePort
  selector:
    app: boardgame
  ports:
    - port: 80
      targetPort: 8082
      nodePort: 30480
